/* ------------------------------------------------------------------ *
 * A fictional SOC 1 Type 2 report, rendered by the mock PDF viewer.
 *
 * Every source quotation used by the extractors is defined once in `Q`
 * and interpolated into the page text below, so a highlight always has
 * something real to land on.
 * ------------------------------------------------------------------ */

export type PdfBlock =
  | { t: 'h1' | 'h2' | 'h3'; text: string }
  | { t: 'p'; text: string }
  | { t: 'li'; text: string }
  | { t: 'note'; text: string }
  | { t: 'table'; head: string[]; rows: string[][] }
  | { t: 'spacer' }

export interface PdfPage {
  n: number
  label: string
  blocks: PdfBlock[]
}

/** Verbatim strings the extractors cite. Keep these unique enough to match on. */
export const Q = {
  serviceOrg:
    'Northwind Payroll Services, Inc. (“Northwind” or the “Service Organization”)',
  application:
    'the Northwind PayCycle payroll processing platform (the “System”)',
  reportType:
    'Report on Controls at a Service Organization Relevant to User Entities’ Internal Control over Financial Reporting (SOC 1® Type 2)',
  period:
    'throughout the period October 1, 2024 to September 30, 2025',
  auditorFirm: 'Braddock & Whitfield LLP',
  opinion:
    'In our opinion, in all material respects, the controls stated in the description were suitably designed and operated effectively throughout the period October 1, 2024 to September 30, 2025 to provide reasonable assurance that the control objectives stated in the description would be achieved.',
  opinionDate: 'Portland, Oregon — November 14, 2025',
  locations:
    'Services are delivered from Northwind facilities in Portland, Oregon and Columbus, Ohio, with disaster recovery capability in Reno, Nevada.',
  gapNote:
    'This report covers the twelve-month period ended September 30, 2025. No gap exists between this report and the prior period report, which covered October 1, 2023 to September 30, 2024.',
  bridge:
    'A bridge letter covering October 1, 2025 through December 31, 2025 is available upon request from the Northwind compliance team.',
  // subservice
  subCarve:
    'Northwind uses Meridian Cloud Infrastructure, LLC for data center hosting and infrastructure services. Northwind applies the carve-out method; controls at Meridian are not included in the scope of this report.',
  subInclusive:
    'Northwind uses Calder Trust Bank, N.A. for payroll disbursement and settlement services. The inclusive method has been applied and Calder Trust Bank controls are presented in Section IV.',
  subTaxCarve:
    'Tax filing and remittance services are performed by Ashfield Tax Solutions, Inc. under the carve-out method.',
  // CUECs
  cuec1:
    'User entities are responsible for establishing controls to ensure that employee master data, including new hires, terminations, and pay rate changes, is submitted to Northwind completely, accurately, and on a timely basis.',
  cuec2:
    'User entities are responsible for reviewing the payroll register and variance report made available in PayCycle prior to authorizing each payroll disbursement.',
  cuec3:
    'User entities are responsible for provisioning, periodically reviewing, and promptly removing user access to PayCycle for their own personnel.',
  cuec4:
    'User entities are responsible for reconciling payroll expense and liability accounts recorded in their general ledger to the reports generated by PayCycle each period.',
  cuec5:
    'User entities are responsible for notifying Northwind of changes to authorized approvers and banking instructions through the designated secure channel.',
  // objectives
  co1: 'Controls provide reasonable assurance that new payroll data and changes to existing payroll data are authorized by the user entity and recorded completely and accurately.',
  co2: 'Controls provide reasonable assurance that payroll calculations, including gross-to-net, statutory deductions, and employer contributions, are performed completely and accurately.',
  co3: 'Controls provide reasonable assurance that payroll disbursements are made to authorized recipients in the correct amount and within the scheduled settlement window.',
  co4: 'Controls provide reasonable assurance that logical access to the System and to payroll data is restricted to authorized personnel.',
  co5: 'Controls provide reasonable assurance that changes to the System are authorized, tested, and approved prior to migration into the production environment.',
  // activities
  ca11: 'Employee master data changes submitted through the PayCycle portal require electronic authorization by a designated user entity approver before the change is applied to the payroll master file.',
  ca12: 'A daily automated exception report identifies master data changes applied without a matching approval record. The Payroll Operations supervisor investigates and clears all items on the report.',
  ca21: 'Gross-to-net calculation logic is configured centrally and validated against an independent calculation engine each pay cycle. Variances greater than $0.01 are researched and resolved before the register is released.',
  ca22: 'Statutory tax tables are updated from the vendor feed and reviewed by a Payroll Tax analyst prior to activation in the production environment.',
  ca31: 'Disbursement files transmitted to Calder Trust Bank are protected by a control total and hash comparison. Files failing validation are rejected and re-transmitted after investigation.',
  ca41: 'Access to the PayCycle production environment is granted based on documented role definitions and approved by the application owner.',
  ca42: 'A quarterly user access review is performed by the application owner. Access identified as no longer required is removed within ten business days.',
  ca51: 'Program changes are documented in the change management system, tested in a non-production environment, and approved by the release manager prior to migration.',
  // test results / exceptions
  test41:
    'For a sample of 25 access grants, we inspected the access request record and observed evidence of approval by the application owner prior to provisioning.',
  ex1Result:
    'For 2 of the 4 quarterly user access reviews selected for testing, the review was completed 18 and 24 days after the scheduled quarter-end due date. Access removals identified by those reviews were processed within the required ten business days once the review was completed.',
  ex1Mgmt:
    'Management acknowledges the delay in completing two quarterly access reviews. A calendar-driven workflow with automated escalation to the application owner was implemented in August 2025 to enforce the review due date.',
  ex2Result:
    'For 1 of the 40 program changes selected for testing, evidence of release manager approval could not be located, although testing evidence and a documented change record were present.',
  ex2Mgmt:
    'Management determined the change was a low-risk cosmetic update to a report header and was reviewed by the development lead. The approval record was not retained. Change management training was re-delivered to the release team in September 2025.',
  ex3Result:
    'For 3 of the 30 tax table updates selected for testing, the Payroll Tax analyst review was evidenced after the table had been activated in production. No calculation errors resulted from these three updates.',
  ex3Mgmt:
    'Management has reconfigured the tax table workflow to prevent activation until the analyst review is recorded. The change was deployed on July 22, 2025.',
  // vendors
  vendor1: 'Meridian Cloud Infrastructure, LLC — data center hosting and managed infrastructure',
  vendor2: 'Calder Trust Bank, N.A. — payroll settlement and disbursement',
  vendor3: 'Ashfield Tax Solutions, Inc. — payroll tax filing and remittance',
  vendor4: 'Halloway Print & Mail Services, LLC — pay statement printing and distribution',
  vendor5: 'Verity Identity Systems, Inc. — multi-factor authentication services',
}

export const PDF_PAGE_COUNT = 18

export const pdfPages: PdfPage[] = [
  {
    n: 1,
    label: 'Cover',
    blocks: [
      { t: 'spacer' },
      { t: 'h1', text: 'Northwind Payroll Services, Inc.' },
      { t: 'h2', text: Q.reportType },
      { t: 'spacer' },
      { t: 'p', text: 'Description of the Northwind PayCycle System and the suitability of the design and operating effectiveness of controls' },
      { t: 'p', text: `For the period ${'October 1, 2024 to September 30, 2025'}` },
      { t: 'spacer' },
      { t: 'p', text: `Independent Service Auditor: ${Q.auditorFirm}` },
      { t: 'note', text: 'This report is intended solely for the information and use of Northwind Payroll Services, Inc., its user entities, and the independent auditors of those user entities.' },
    ],
  },
  {
    n: 2,
    label: 'Table of contents',
    blocks: [
      { t: 'h2', text: 'Table of Contents' },
      {
        t: 'table',
        head: ['Section', 'Description', 'Page'],
        rows: [
          ['I', "Independent Service Auditor's Report", '3'],
          ['II', "Management's Assertion", '6'],
          ['III', 'Description of the System', '7'],
          ['IV', 'Control Objectives, Controls, and Tests of Controls', '11'],
          ['V', 'Other Information Provided by Northwind', '18'],
        ],
      },
    ],
  },
  {
    n: 3,
    label: "Service Auditor's Report",
    blocks: [
      { t: 'h2', text: "Section I — Independent Service Auditor's Report" },
      { t: 'p', text: 'To the Management of Northwind Payroll Services, Inc.:' },
      { t: 'h3', text: 'Scope' },
      { t: 'p', text: `We have examined ${Q.serviceOrg} description of ${Q.application} for processing user entities' transactions ${Q.period}, and the suitability of the design and operating effectiveness of controls stated in the description.` },
      { t: 'p', text: Q.locations },
      { t: 'p', text: Q.subCarve },
      { t: 'p', text: Q.subInclusive },
    ],
  },
  {
    n: 4,
    label: "Service Auditor's Report (cont.)",
    blocks: [
      { t: 'h3', text: "Service Organization's Responsibilities" },
      { t: 'p', text: 'Northwind is responsible for preparing the description and its assertion, including the completeness, accuracy, and method of presentation of the description and assertion, providing the services covered by the description, specifying the control objectives and stating them in the description, identifying the risks that threaten the achievement of the control objectives, and designing, implementing, and documenting controls that are suitably designed and operating effectively to achieve the related control objectives.' },
      { t: 'h3', text: "Service Auditor's Responsibilities" },
      { t: 'p', text: 'Our responsibility is to express an opinion on the description and on the suitability of design and operating effectiveness of the controls stated in the description, based on our examination. Our examination was conducted in accordance with attestation standards established by the American Institute of Certified Public Accountants.' },
      { t: 'h3', text: 'Inherent Limitations' },
      { t: 'p', text: 'Because of their nature, controls at a service organization may not prevent, or detect and correct, all misstatements in processing or reporting transactions. Also, the projection to the future of any evaluation of the fairness of the presentation of the description, or conclusions about the suitability of the design or operating effectiveness of the controls, is subject to the risk that controls at a service organization may become ineffective.' },
    ],
  },
  {
    n: 5,
    label: 'Opinion',
    blocks: [
      { t: 'h3', text: 'Opinion' },
      { t: 'p', text: Q.opinion },
      { t: 'p', text: 'The specific controls tested and the nature, timing, and results of those tests are presented in Section IV of this report.' },
      { t: 'h3', text: 'Restricted Use' },
      { t: 'p', text: 'This report is intended solely for the information and use of Northwind, user entities of the System during some or all of the period, and their auditors who have a sufficient understanding to consider it, along with other information, in obtaining an understanding of user entities’ information and communication systems relevant to financial reporting.' },
      { t: 'spacer' },
      { t: 'p', text: Q.auditorFirm },
      { t: 'p', text: Q.opinionDate },
    ],
  },
  {
    n: 6,
    label: "Management's Assertion",
    blocks: [
      { t: 'h2', text: "Section II — Management's Assertion" },
      { t: 'p', text: 'We have prepared the accompanying description of the Northwind PayCycle System for user entities of the System during the period October 1, 2024 to September 30, 2025, and their user auditors who have a sufficient understanding to consider it, along with other information, including information about controls implemented by user entities of the System themselves.' },
      { t: 'p', text: 'We confirm, to the best of our knowledge and belief, that the description fairly presents the System made available to user entities during the period, the controls stated in the description were suitably designed to provide reasonable assurance that the control objectives would be achieved, and the controls stated in the description operated effectively throughout the period.' },
      { t: 'p', text: Q.gapNote },
    ],
  },
  {
    n: 7,
    label: 'System description',
    blocks: [
      { t: 'h2', text: 'Section III — Description of the System' },
      { t: 'h3', text: 'Company Overview' },
      { t: 'p', text: 'Northwind Payroll Services, Inc. provides outsourced payroll processing, payroll tax administration, and disbursement services to approximately 1,850 user entities across the United States. Northwind processes an average of 4.2 million pay statements per calendar quarter.' },
      { t: 'h3', text: 'Services Provided' },
      { t: 'li', text: 'Collection and validation of employee master data and time entry data submitted by user entities.' },
      { t: 'li', text: 'Gross-to-net payroll calculation, including statutory withholding and employer contributions.' },
      { t: 'li', text: 'Generation of payroll registers, variance reports, and general ledger interface files.' },
      { t: 'li', text: 'Initiation of payroll disbursements and remittance of payroll taxes.' },
    ],
  },
  {
    n: 8,
    label: 'Subservice organizations',
    blocks: [
      { t: 'h3', text: 'Subservice Organizations' },
      { t: 'p', text: Q.subCarve },
      { t: 'p', text: Q.subInclusive },
      { t: 'p', text: Q.subTaxCarve },
      { t: 'p', text: 'Northwind performs the following monitoring activities over carved-out subservice organizations: annual review of the subservice organization SOC report, review of complementary subservice organization controls, and periodic service level reporting.' },
    ],
  },
  {
    n: 9,
    label: 'Complementary User Entity Controls',
    blocks: [
      { t: 'h3', text: 'Complementary User Entity Controls' },
      { t: 'p', text: 'The control objectives stated in this description can be achieved only if the complementary user entity controls contemplated in the design of Northwind’s controls are suitably designed and operating effectively. The following complementary user entity controls should be implemented by user entities:' },
      { t: 'li', text: `CUEC-1. ${Q.cuec1}` },
      { t: 'li', text: `CUEC-2. ${Q.cuec2}` },
      { t: 'li', text: `CUEC-3. ${Q.cuec3}` },
    ],
  },
  {
    n: 10,
    label: 'Complementary User Entity Controls (cont.)',
    blocks: [
      { t: 'li', text: `CUEC-4. ${Q.cuec4}` },
      { t: 'li', text: `CUEC-5. ${Q.cuec5}` },
      { t: 'h3', text: 'Third Parties and Vendors' },
      { t: 'p', text: 'The following third parties support delivery of the System:' },
      { t: 'li', text: Q.vendor1 },
      { t: 'li', text: Q.vendor2 },
      { t: 'li', text: Q.vendor3 },
      { t: 'li', text: Q.vendor4 },
      { t: 'li', text: Q.vendor5 },
    ],
  },
  {
    n: 11,
    label: 'Control objective 1',
    blocks: [
      { t: 'h2', text: 'Section IV — Control Objectives, Controls, and Tests of Controls' },
      { t: 'h3', text: 'Control Objective 1 — Data Input and Authorization' },
      { t: 'p', text: Q.co1 },
      {
        t: 'table',
        head: ['Control', 'Control activity', 'Test performed', 'Results'],
        rows: [
          ['1.1', Q.ca11, 'For a sample of 40 master data changes, inspected the authorization record retained in the PayCycle portal.', 'No exceptions noted.'],
          ['1.2', Q.ca12, 'For a sample of 25 days, inspected the exception report and evidence of supervisor clearance.', 'No exceptions noted.'],
        ],
      },
    ],
  },
  {
    n: 12,
    label: 'Control objective 2',
    blocks: [
      { t: 'h3', text: 'Control Objective 2 — Payroll Calculation' },
      { t: 'p', text: Q.co2 },
      {
        t: 'table',
        head: ['Control', 'Control activity', 'Test performed', 'Results'],
        rows: [
          ['2.1', Q.ca21, 'For a sample of 26 pay cycles, inspected the independent calculation comparison and evidence of variance resolution.', 'No exceptions noted.'],
          ['2.2', Q.ca22, 'For a sample of 30 tax table updates, inspected evidence of analyst review prior to activation.', `Exceptions noted. ${Q.ex3Result}`],
        ],
      },
    ],
  },
  {
    n: 13,
    label: 'Control objective 3',
    blocks: [
      { t: 'h3', text: 'Control Objective 3 — Disbursement' },
      { t: 'p', text: Q.co3 },
      {
        t: 'table',
        head: ['Control', 'Control activity', 'Test performed', 'Results'],
        rows: [
          ['3.1', Q.ca31, 'For a sample of 30 disbursement files, inspected the control total and hash validation log.', 'No exceptions noted.'],
          ['3.2', 'Settlement confirmations received from Calder Trust Bank are reconciled to the disbursement register each business day by Treasury Operations.', 'For a sample of 25 business days, inspected the completed reconciliation and evidence of review.', 'No exceptions noted.'],
        ],
      },
    ],
  },
  {
    n: 14,
    label: 'Control objective 4',
    blocks: [
      { t: 'h3', text: 'Control Objective 4 — Logical Access' },
      { t: 'p', text: Q.co4 },
      {
        t: 'table',
        head: ['Control', 'Control activity', 'Test performed', 'Results'],
        rows: [
          ['4.1', Q.ca41, Q.test41, 'No exceptions noted.'],
          ['4.2', Q.ca42, 'For all 4 quarterly user access reviews performed during the period, inspected the completed review and evidence of access removal.', `Exceptions noted. ${Q.ex1Result}`],
        ],
      },
    ],
  },
  {
    n: 15,
    label: 'Control objective 5',
    blocks: [
      { t: 'h3', text: 'Control Objective 5 — Change Management' },
      { t: 'p', text: Q.co5 },
      {
        t: 'table',
        head: ['Control', 'Control activity', 'Test performed', 'Results'],
        rows: [
          ['5.1', Q.ca51, 'For a sample of 40 program changes, inspected the change record, test evidence, and release manager approval.', `Exceptions noted. ${Q.ex2Result}`],
        ],
      },
    ],
  },
  {
    n: 16,
    label: 'Summary of exceptions',
    blocks: [
      { t: 'h3', text: 'Summary of Testing Exceptions' },
      {
        t: 'table',
        head: ['Ref', 'Control', 'Exception'],
        rows: [
          ['EX-1', '4.2', Q.ex1Result],
          ['EX-2', '5.1', Q.ex2Result],
          ['EX-3', '2.2', Q.ex3Result],
        ],
      },
      { t: 'note', text: 'The service auditor concluded that the exceptions noted above, individually and in the aggregate, did not prevent the related control objectives from being achieved.' },
    ],
  },
  {
    n: 17,
    label: 'Management responses',
    blocks: [
      { t: 'h3', text: "Management's Responses to Testing Exceptions" },
      { t: 'p', text: `EX-1. ${Q.ex1Mgmt}` },
      { t: 'p', text: `EX-2. ${Q.ex2Mgmt}` },
      { t: 'p', text: `EX-3. ${Q.ex3Mgmt}` },
    ],
  },
  {
    n: 18,
    label: 'Other information',
    blocks: [
      { t: 'h2', text: 'Section V — Other Information Provided by Northwind' },
      { t: 'p', text: 'The information in this section is presented by Northwind to provide additional context and has not been subjected to the procedures applied in the examination of the description of the System.' },
      { t: 'p', text: Q.bridge },
      { t: 'p', text: 'Business continuity testing was performed in March 2025 with a recovery time objective of four hours. The test met the stated objective.' },
    ],
  },
]

/* ------------------------------------------------------------------ *
 * Qualified-opinion variant of the same engagement. Only the opinion
 * page and the exception summary differ, which is what a reissued
 * report with a scope limitation looks like in practice.
 * ------------------------------------------------------------------ */

export const QQ = {
  opinion:
    'In our opinion, except for the matter described in the Basis for Qualified Opinion paragraph, in all material respects, the controls stated in the description were suitably designed and operated effectively throughout the period October 1, 2024 to September 30, 2025 to provide reasonable assurance that the control objectives stated in the description would be achieved.',
  basis:
    'The control activity described as control 3.1 was not operating effectively throughout the period. For the four months from February 2025 through May 2025, the control total and hash comparison over outbound disbursement files was disabled following a platform upgrade. As a result, control objective 3 was not achieved for that portion of the period.',
  ex4Result:
    'For 9 of the 30 disbursement files selected for testing, the control total and hash validation log contained no validation entry. Northwind confirmed the validation routine was disabled between February 3, 2025 and May 28, 2025.',
  ex4Mgmt:
    'Management identified the disabled validation routine during a platform health review in May 2025 and restored it on May 28, 2025. A retrospective reconciliation of all disbursement files processed during the affected window was completed in June 2025 and identified no incorrect disbursements.',
  opinionDate: 'Portland, Oregon — December 2, 2025',
}

const qualifiedOpinionPage: PdfPage = {
  n: 5,
  label: 'Qualified opinion',
  blocks: [
    { t: 'h3', text: 'Basis for Qualified Opinion' },
    { t: 'p', text: QQ.basis },
    { t: 'h3', text: 'Qualified Opinion' },
    { t: 'p', text: QQ.opinion },
    { t: 'spacer' },
    { t: 'p', text: Q.auditorFirm },
    { t: 'p', text: QQ.opinionDate },
  ],
}

const qualifiedExceptionPage: PdfPage = {
  n: 16,
  label: 'Summary of exceptions',
  blocks: [
    { t: 'h3', text: 'Summary of Testing Exceptions' },
    {
      t: 'table',
      head: ['Ref', 'Control', 'Exception'],
      rows: [
        ['EX-1', '4.2', Q.ex1Result],
        ['EX-2', '5.1', Q.ex2Result],
        ['EX-3', '2.2', Q.ex3Result],
        ['EX-4', '3.1', QQ.ex4Result],
      ],
    },
    { t: 'note', text: 'Exception EX-4 resulted in control objective 3 not being achieved for the period February 3, 2025 through May 28, 2025 and is the basis for the qualified opinion.' },
  ],
}

export const pdfPagesQualified: PdfPage[] = pdfPages.map((p) =>
  p.n === 5 ? qualifiedOpinionPage : p.n === 16 ? qualifiedExceptionPage : p,
)

export type DocumentId = 'standard' | 'qualified'

export function getPages(doc: DocumentId): PdfPage[] {
  return doc === 'qualified' ? pdfPagesQualified : pdfPages
}
